analyzer:
  errors:
    avoid_catches_without_on_clauses: ignore
    avoid_print: ignore
    deprecated_member_use: ignore
    document_ignores: ignore
    lines_longer_than_80_chars: ignore
include: package:very_good_analysis/analysis_options.9.0.0.yaml
linter:
  rules:
    public_member_api_docs: false