name: deploy

# Run this workflow when a new release is published
on:
  release:
    types: [published]
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest # Use the latest version of Ubuntu

    steps:
      # 1. Checkout the repository code
      - name: Checkout
        uses: actions/checkout@v3

      # 2. Setup Flutter SDK
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # Use the stable channel of Flutter
          cache: false
          
      # 3. Get Flutter dependencies
      - name: Get dependencies
        run: flutter pub get

      # 4. Build the Flutter web app
      - name: Build Web App
        run: flutter build web --release --base-href /ht-dashboard/

      # 5. Deploy the built app to GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web